server:
  port: 80
############################################################
#
# 配置数据源信息 生产环境如变动，可在此处修改
# 对于URL地址，如果后台和数据库都是部署在同一台服务器上，那么locahost没问题，但如果是分别部署的话，需要改动URL
#
############################################################
spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect&useSSL=false
    username: root
    password: 123456